### ISSUE TITLE
predicti label of new data

### ISSUE THREAD

**Issue by JB0527** [ni-inha/Deep-Learning-Models-for-Fall-Classification#1]
안녕하세요 새로운 모델을 학습하기위해 이 레포를 참고하고 있습니다. 

현재는, 정답값이 없는 새로운 테스트 데이터에 대해 predict를 하려고 합니다. 

이 때, sentence를 convert_feature 할 때, label 값이 있어야만 가능한 것으로 보이는데, 이 label 값이 convert함수에는 필요할 지 모르나 predict에는 쓰이지는 않으니 일단 데이터셋을 만드는 건지 아니면, 따로 predict 방법이 있는 건지 궁금합니다.

현재는 따로  convert_feature 함수를 임의로 수정해서 predict함수에 쓰이도록 만들었습니다.

감사합니다!

**Comment by oneonlee** [comment]
우선, 정보의 축약 없이 질문을 최대한 상세하게 해주시길 부탁드립니다.

라벨링이 되지 않은 새로운 테스트 데이터에 대해서 추론하는 것은 가능합니다. 

https://github.com/ni-inha/Automatic-identification-system-for-fall-event-records-in-EMR-clinical-notes/blob/main/main.py

위 코드에 추론용 코드를 이미 개발했으니 참고해주세요.

혹시라도 질문이 해결되지 않았다면 말씀해주세요.
